/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_highradius_interop_App */

#ifndef _Included_com_highradius_interop_App
#define _Included_com_highradius_interop_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_highradius_interop_App
 * Method:    readCsv
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_highradius_interop_App_readCsv
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
